# Generated by Django 5.2.5 on 2025-11-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_plate",
                    models.CharField(
                        help_text="Vehicle registration number (e.g., KL-01-AB-1234)",
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=40, help_text="Total number of seats"
                    ),
                ),
                (
                    "mileage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Fuel efficiency in km/liter",
                        max_digits=5,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("all_stop", "All Stop Service"),
                            ("limited_stop", "Limited Stop Service"),
                            ("express", "Express Service"),
                        ],
                        default="all_stop",
                        help_text="Type of service this bus provides",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether bus is operational"
                    ),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Current GPS latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Current GPS longitude",
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "last_location_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="When location was last updated",
                        null=True,
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False, help_text="Is bus currently on route"
                    ),
                ),
                (
                    "current_route",
                    models.ForeignKey(
                        blank=True,
                        help_text="Route currently being served",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus",
                "verbose_name_plural": "Buses",
                "ordering": ["number_plate"],
            },
        ),
        migrations.CreateModel(
            name="BusSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of assignment")),
                (
                    "start_time",
                    models.TimeField(help_text="When bus starts this route"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="When bus finishes this route"),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        help_text="Bus being assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_schedules",
                        to="schedules.bus",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Route being served",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_schedules",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Assignment",
                "verbose_name_plural": "Bus Assignments",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the trip")),
                (
                    "departure_time",
                    models.TimeField(help_text="Start time from origin"),
                ),
                (
                    "arrival_time",
                    models.TimeField(help_text="Approximate arrival at destination"),
                ),
                (
                    "total_seats",
                    models.PositiveIntegerField(
                        help_text="Total available seats (usually equals bus capacity)"
                    ),
                ),
                (
                    "available_seats",
                    models.PositiveIntegerField(help_text="Currently available seats"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        help_text="Bus assigned to this schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="schedules.bus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "ordering": ["date", "departure_time"],
            },
        ),
    ]
