# Generated by Django 5.2.5 on 2025-11-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Route number (e.g., 101, 102)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Route name (e.g., Downtown Express)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional route description", null=True
                    ),
                ),
                (
                    "origin",
                    models.CharField(help_text="Starting point", max_length=100),
                ),
                (
                    "destination",
                    models.CharField(help_text="Ending point", max_length=100),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total distance in kilometers",
                        max_digits=6,
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Duration of trip in hours (e.g., 1.5 for 1 hour 30 minutes)",
                        max_digits=4,
                    ),
                ),
                (
                    "turnaround_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.33,
                        help_text="Turnaround time at terminal in hours (e.g., 0.33 for 20 minutes)",
                        max_digits=4,
                    ),
                ),
                (
                    "buffer_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.16,
                        help_text="Buffer time for delays in hours (e.g., 0.16 for 10 minutes)",
                        max_digits=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Stop name (e.g., Central Library, Maple St & 5th Ave)",
                        max_length=100,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Order of stop on the route (1, 2, 3...)"
                    ),
                ),
                (
                    "distance_from_origin",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance from route start in kilometers",
                        max_digits=6,
                    ),
                ),
                (
                    "is_limited_stop",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a major stop served by limited stop buses",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Route this stop belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stop",
                "verbose_name_plural": "Stops",
                "ordering": ["route", "sequence"],
                "unique_together": {("route", "name"), ("route", "sequence")},
            },
        ),
    ]
