# Generated by Django 5.2.5 on 2025-11-26 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demand", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="demandalert",
            name="user",
            field=models.ForeignKey(
                help_text="Passenger reporting the crowd",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demand_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="demandalert",
            index=models.Index(
                fields=["created_at", "status"], name="demand_dema_created_a58d83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demandalert",
            index=models.Index(
                fields=["stop", "status"], name="demand_dema_stop_id_762a46_idx"
            ),
        ),
    ]
