# Generated by Django 5.2.5 on 2025-11-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreInform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_travel",
                    models.DateField(help_text="Date passenger plans to travel"),
                ),
                ("desired_time", models.TimeField(help_text="Preferred boarding time")),
                (
                    "passenger_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of passengers traveling"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("noted", "Noted by Controller"),
                            ("completed", "Journey Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of pre-inform",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When pre-inform was submitted"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boarding_stop",
                    models.ForeignKey(
                        help_text="Stop where passenger will board",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_passengers",
                        to="routes.stop",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Route passenger intends to take",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preinforms",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Inform",
                "verbose_name_plural": "Pre-Informs",
                "ordering": ["-created_at"],
            },
        ),
    ]
