# Generated by Django 5.2.5 on 2025-11-26 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preinforms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preinform",
            name="user",
            field=models.ForeignKey(
                help_text="Passenger submitting the pre-inform",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preinforms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="preinform",
            index=models.Index(
                fields=["date_of_travel", "route"],
                name="preinforms__date_of_640d0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="preinform",
            index=models.Index(fields=["status"], name="preinforms__status_b1b1dc_idx"),
        ),
    ]
