# Generated by Django 5.2.5 on 2025-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(
                        help_text="Start date (Monday) of the week being recorded"
                    ),
                ),
                (
                    "estimated_passengers",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated passengers from PreInform data (auto-calculated)",
                    ),
                ),
                (
                    "actual_passengers",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Actual passengers from ticket sales (manually entered)",
                    ),
                ),
                (
                    "total_passengers",
                    models.PositiveIntegerField(
                        help_text="Total passengers (estimated + actual, auto-calculated)"
                    ),
                ),
                (
                    "total_kms",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total kilometers traveled this week",
                        max_digits=10,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total revenue earned (auto-calculated)",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total operational cost (auto-calculated)",
                        max_digits=10,
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Net profit (revenue - cost, auto-calculated)",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Weekly Performance",
                "verbose_name_plural": "Weekly Performances",
                "ordering": ["-week_start_date", "bus"],
            },
        ),
    ]
