# Generated by Django 5.2.5 on 2025-11-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        ("routes", "0001_initial"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyperformance",
            name="bus",
            field=models.ForeignKey(
                help_text="Bus being tracked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_performances",
                to="schedules.bus",
            ),
        ),
        migrations.AddField(
            model_name="weeklyperformance",
            name="route",
            field=models.ForeignKey(
                help_text="Route being served",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_performances",
                to="routes.route",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyperformance",
            index=models.Index(
                fields=["week_start_date"], name="operations__week_st_ee6a29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyperformance",
            index=models.Index(
                fields=["bus", "week_start_date"], name="operations__bus_id_cafcb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyperformance",
            index=models.Index(
                fields=["route", "week_start_date"],
                name="operations__route_i_688aaf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weeklyperformance",
            unique_together={("bus", "route", "week_start_date")},
        ),
    ]
