# Generated by Django 5.2.5 on 2025-11-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_people",
                    models.PositiveIntegerField(
                        help_text="Approximate number of people waiting (including reporter)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("verified", "Verified by Admin"),
                            ("dispatched", "Bus Dispatched"),
                            ("resolved", "Resolved"),
                            ("expired", "Expired"),
                        ],
                        default="reported",
                        help_text="Current status of alert",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When alert was created"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this alert expires (1 hour from creation)"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When alert was resolved", null=True
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notes from control room"),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        help_text="Stop where people are waiting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_alerts",
                        to="routes.stop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand Alert",
                "verbose_name_plural": "Demand Alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
