# Generated by Django 5.2.5 on 2025-11-26 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routes", "0001_initial"),
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="driver",
            field=models.ForeignKey(
                help_text="Driver assigned to this schedule",
                limit_choices_to={"role": "driver"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="route",
            field=models.ForeignKey(
                help_text="Route for this schedule",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="routes.route",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="current_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Current active schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_buses",
                to="schedules.schedule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={
                ("bus", "date", "departure_time"),
                ("driver", "date", "departure_time"),
            },
        ),
    ]
